# Generated by Django 4.2.7 on 2023-11-23 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_at']},
        ),
    ]
