# Generated by Django 4.2.7 on 2023-11-24 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at']},
        ),
    ]
